# Generated by Django 4.1.3 on 2022-12-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='masail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deskripsi', models.CharField(max_length=100)),
                ('Jawaban', models.CharField(max_length=50)),
                ('Tanggapan', models.CharField(max_length=50)),
            ],
        ),
    ]
