# Generated by Django 4.1.3 on 2023-01-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masail',
            name='keputusan',
            field=models.IntegerField(null=True),
        ),
    ]
